### ISSUE TITLE
Running cluster randomly going undetected

### ISSUE THREAD

**Issue by aljabadi** [databricks/databricks-vscode#459] opened 2023-02-16 04:14 UTC
Thank you for this fabulous extension!

While the cluster is running, the extension is at times unable to detect it.

![image](https://user-images.githubusercontent.com/28503057/219266233-f5bf92b0-b9a2-435b-8de8-567863997f49.png)

It is also not possible to use 'Run File on Databricks'

This behaviour is somewhat erratic.

System Info: VSCode v1.75.1 on Windows 10 (using a devcontainer)
Login using Azure CLI.

**Comment by fjakobs** [comment] 2023-02-16 12:32
Thanks for reporting this issue. I'll try to reproduce.

**Comment by kartikgupta-db** [comment] 2023-03-14 03:48
Closing since unable to reproduce.

**Closed** 2023-03-14 03:48 UTC
Labels: bug
