### ISSUE TITLE
Not showing the existing repos and creating a new repo throws authentication error

### ISSUE THREAD

**Issue by ajith428** [databricks/databricks-vscode#508] opened 2023-02-25 20:55 UTC
![Screenshot (3)](https://user-images.githubusercontent.com/26915308/221380369-4f044783-8ff4-4f40-b118-32624b088951.jpg)
Databricks for visual studio code(Sync Destination) is not showing existing Databricks Repos and when creating a new repo It throws an authentication error.

Error: error_code: PERMISSION_DENIED, message: Missing Git provider credentials. Go to User settings > Git Integration to add your personal access token.

GitHub Enterprise Access Token is added to the Databricks Git Integration plugin. Cloned my-repo to Databricks Repo using the access token.

Databricks is creating a repo under Repo/someone@example.com/ But it should be Repos/someone@example.com/ missing S. Will it cause the error?
Or Is it not integrated with GitHub Enterprise?

**Comment by kartikgupta-db** [comment] 2023-02-27 11:41
Hi. We made a decision to only show repos that are created from the extension. This was because syncing local code overwrites remote code which could lead to users losing their existing data. (https://github.com/databricks/databricks-vscode/pull/478)

There are 2 possibilities here
1. Add the requested github token and setup that integration. We use an empty, readonly github repo to create an empty Databricks Repo from the IDE, but we need the github integration for that.
2. For using existing repos, you can edit `.databricks/project.json` with the desired repo path. This is discouraged because of the above mentioned reason. 

The intended experience is to treat Databricks Repos as a code staging container, from where clusters can pick up the code to run. In future we will move all of this to a standard workspace folder. If your workflow requires using existing Repos please do reach out to discuss it.

**Comment by kartikgupta-db** [comment] 2023-02-27 11:45
>Databricks is creating a repo under Repo/[someone@example.com](mailto:someone@example.com)/ But it should be Repos/[someone@example.com](mailto:someone@example.com)/ missing S. Will it cause the error?

Nope. This is just a typo in the UI.

**Comment by ajith428** [comment] 2023-03-02 02:48
How to retrieve debug logs.

**Comment by kartikgupta-db** [comment] 2023-03-03 11:19
@ajith428 you can get the debug logs from [here](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

**Comment by kartikgupta-db** [comment] 2023-03-20 14:09
duplicate of #575

**Closed by kartikgupta-db** 2023-03-20 14:09 UTC
Labels: bug
